/**
 * 
 * This file was automatically generated by the Repast Simphony Agent Editor.
 * Please see http://repast.sourceforge.net/ for details.
 * 
 */

/**
 *
 * Set the package name.
 *
 */
package ecosystem

/**
 *
 * Import the needed packages.
 *
 */
import java.io.*
import java.math.*
import java.util.*
import javax.measure.unit.*
import org.jscience.mathematics.number.*
import org.jscience.mathematics.vector.*
import org.jscience.physics.amount.*
import repast.simphony.adaptation.neural.*
import repast.simphony.adaptation.regression.*
import repast.simphony.context.*
import repast.simphony.context.space.continuous.*
import repast.simphony.context.space.gis.*
import repast.simphony.context.space.graph.*
import repast.simphony.context.space.grid.*
import repast.simphony.engine.environment.*
import repast.simphony.engine.schedule.*
import repast.simphony.engine.watcher.*
import repast.simphony.groovy.math.*
import repast.simphony.integration.*
import repast.simphony.matlab.link.*
import repast.simphony.query.*
import repast.simphony.query.space.continuous.*
import repast.simphony.query.space.gis.*
import repast.simphony.query.space.graph.*
import repast.simphony.query.space.grid.*
import repast.simphony.query.space.projection.*
import repast.simphony.parameter.*
import repast.simphony.random.*
import repast.simphony.space.continuous.*
import repast.simphony.space.gis.*
import repast.simphony.space.graph.*
import repast.simphony.space.grid.*
import repast.simphony.space.projection.*
import repast.simphony.ui.probe.*
import repast.simphony.util.*
import simphony.util.messages.*
import static java.lang.Math.*
import static repast.simphony.essentials.RepastEssentials.*

/**
 *
 * Platform of cloud mfg
 *
 */
public class CloudPlatform  {

    /**
     *
     * User list to record the user exist in the platform
     * @field userList
     *
     */
    @Parameter (displayName = "User List", usageName = "userList")
    public ArrayList getUserList() {
        return userList
    }
    public void setUserList(ArrayList newValue) {
        userList = newValue
    }
    public ArrayList userList = new ArrayList()

    /**
     *
     * This is an agent property.
     * @field mean1
     *
     */
    @Parameter (displayName = "Mean1", usageName = "mean1")
    public double getMean1() {
        return mean1
    }
    public void setMean1(double newValue) {
        mean1 = newValue
    }
    public double mean1 = 0.16

    /**
     *
     * Count the fininshed jobs
     * @field finishCount
     *
     */
    @Parameter (displayName = "Finish Count", usageName = "finishCount")
    public int getFinishCount() {
        return finishCount
    }
    public void setFinishCount(int newValue) {
        finishCount = newValue
    }
    public int finishCount = 0

    /**
     *
     * Count the fininshed jobs
     * @field serviceGeneratedCount
     *
     */
    @Parameter (displayName = "Service Generate count", usageName = "serviceGeneratedCount")
    public int getServiceGeneratedCount() {
        return serviceGeneratedCount
    }
    public void setServiceGeneratedCount(int newValue) {
        serviceGeneratedCount = newValue
    }
    public int serviceGeneratedCount = 0

    /**
     *
     * [type: amount]
     * @field resourceTypeAmount
     *
     */
    @Parameter (displayName = "Resource Map", usageName = "resourceTypeAmount")
    public Map getResourceTypeAmount() {
        return resourceTypeAmount
    }
    public void setResourceTypeAmount(Map newValue) {
        resourceTypeAmount = newValue
    }
    public Map resourceTypeAmount = [:]

    /**
     *
     * This is an agent property.
     * @field resourceList
     *
     */
    @Parameter (displayName = "Resource List registered", usageName = "resourceList")
    public List getResourceList() {
        return resourceList
    }
    public void setResourceList(List newValue) {
        resourceList = newValue
    }
    public List resourceList = []

    /**
     *
     * This value is used to automatically generate agent identifiers.
     * @field serialVersionUID
     *
     */
    private static final long serialVersionUID = 1L

    /**
     *
     * This value is used to automatically generate agent identifiers.
     * @field agentIDCounter
     *
     */
    protected static long agentIDCounter = 1

    /**
     *
     * This value is the agent's identifier.
     * @field agentID
     *
     */
    protected String agentID = "CloudPlatform " + (agentIDCounter++)

    /**
     *
     * Add user including pure and complex users
     * @method addUser
     *
     */
    public void addUser(userID) {

        // Note the simulation time.
        def time = GetTickCountInTimeUnits()

        // This is a task.
        this.userList << userID
    }

    /**
     *
     * Eliminate user include pure and complex users
     * @method EliminateUser
     *
     */
    public void EliminateUser(Object o) {

        // Note the simulation time.
        def time = GetTickCountInTimeUnits()

        // This is a task.
        this.userList.remove(o)
    }

    /**
     *
     * Create provider procedure
     * @method CreateProvider
     *
     */
    public void CreateProvider() {

        // Note the simulation time.
        def time = GetTickCountInTimeUnits()

        // Create Provider at a random distribution
        Provider pagent = new Provider()
        // pagent.GenerateResource(this.typeQuality,this.typeQueueLength)
        pagent.GenerateResource()
        this.addProvider(pagent)
    }

    /**
     *
     * catch the finish task and add the count
     * @method Accumulator
     *
     */
    @Watch(
        watcheeClassName = 'ecosystem.Job',
        watcheeFieldNames = 'finish',
        whenToTrigger = WatcherTriggerSchedule.IMMEDIATE,
        scheduleTriggerDelta = 1d
    )
    public def Accumulator(ecosystem.Job watchedAgent) {

        // Define the return value variable.
        def returnValue

        // Note the simulation time.
        def time = GetTickCountInTimeUnits()


        // This is an agent decision.
        if (watchedAgent.getClass() == ecosystem.Task) {

            // This is a task.
            this.finishCount ++

        } else  {

            // This is a task.
            this.serviceGeneratedCount++

        }
        // Return the results.
        return returnValue

    }

    /**
     *
     * Return the resource quene length sum
     * @method ResourceQueue
     *
     */
    public int ResourceQueue(type) {

        // Define the return value variable.
        def returnValue

        // Note the simulation time.
        def time = GetTickCountInTimeUnits()

        // This is a task.
        int L = 0
        List typeResList = this.resourceList.findAll{ it-> it.getType() == type }

        // This is a loop.
        for (res in typeResList) {

            // This is a task.
            L += res.getQueueLength()

        }

        // This is a task.
        returnValue = L
        // Return the results.
        return returnValue

    }

    /**
     *
     * This is the step behavior.
     * @method ResourceQuality
     *
     */
    public double ResourceQuality(type) {

        // Define the return value variable.
        def returnValue

        // Note the simulation time.
        def time = GetTickCountInTimeUnits()

        // This is a task.
        List typeResList = this.resourceList.findAll{ it-> it.getType() == type }
        double minq = typeResList[0].getQuality()

        // This is a loop.
        for (res in typeResList) {

            // This is a task.
            double theq = res.getQuality()

            // This is an agent decision.
            if (theq < minq) {

                // This is a task.
                minq = theq

            } else  {


            }

        }

        // This is a task.
        returnValue = minq
        // Return the results.
        return returnValue

    }

    /**
     *
     * This is the step behavior.
     * @method addProvider
     *
     */
    public void addProvider(p) {

        // Note the simulation time.
        def time = GetTickCountInTimeUnits()

        // This is a task.
        List resList = p.resourceList.collect()

        // This is a loop.
        for (res in resList) {


            // This is an agent decision.
            if (this.ResourceQueue(res.getType()) == 0) {


                // This is an agent decision.
                if (res.getType() in this.resourceTypeAmount.keySet() && this.ResourceQuality(res.getType()) < res.getQuality()) {

                    // This is a task.
                    p.resourceList.remove(res)

                } else  {


                }

            } else  {


            }

        }


        // This is a loop.
        for (res in p.resourceList) {

            // This is a task.
            AddAgentToContext("Ecosystem", res)
            this.resourceList << res

            // This is an agent decision.
            if (res.getType() in this.resourceTypeAmount.keySet()) {

                // This is a task.
                this.resourceTypeAmount[res.getType()] += res.getCapacity()

            } else  {

                // This is a task.
                this.resourceTypeAmount[res.getType()] = res.getCapacity()

            }

        }


        // This is an agent decision.
        if (p.resourceList.size() > 0) {

            // This is a task.
            AddAgentToContext("Ecosystem", p)

        } else  {


        }
    }

    /**
     *
     * This method provides a human-readable name for the agent.
     * @method toString
     *
     */
    @ProbeID()
    public String toString() {

        // Define the return value variable.
        def returnValue

        // Note the simulation time.
        def time = GetTickCountInTimeUnits()

        // Set the default agent identifier.
        returnValue = this.agentID
        // Return the results.
        return returnValue

    }


}

