/**
 * 
 * This file was automatically generated by the Repast Simphony Agent Editor.
 * Please see http://repast.sourceforge.net/ for details.
 * 
 */

/**
 *
 * Set the package name.
 *
 */
package ecosystem

/**
 *
 * Import the needed packages.
 *
 */
import java.io.*
import java.math.*
import java.util.*
import javax.measure.unit.*
import org.jscience.mathematics.number.*
import org.jscience.mathematics.vector.*
import org.jscience.physics.amount.*
import repast.simphony.adaptation.neural.*
import repast.simphony.adaptation.regression.*
import repast.simphony.context.*
import repast.simphony.context.space.continuous.*
import repast.simphony.context.space.gis.*
import repast.simphony.context.space.graph.*
import repast.simphony.context.space.grid.*
import repast.simphony.engine.environment.*
import repast.simphony.engine.schedule.*
import repast.simphony.engine.watcher.*
import repast.simphony.groovy.math.*
import repast.simphony.integration.*
import repast.simphony.matlab.link.*
import repast.simphony.query.*
import repast.simphony.query.space.continuous.*
import repast.simphony.query.space.gis.*
import repast.simphony.query.space.graph.*
import repast.simphony.query.space.grid.*
import repast.simphony.query.space.projection.*
import repast.simphony.parameter.*
import repast.simphony.random.*
import repast.simphony.space.continuous.*
import repast.simphony.space.gis.*
import repast.simphony.space.graph.*
import repast.simphony.space.grid.*
import repast.simphony.space.projection.*
import repast.simphony.ui.probe.*
import repast.simphony.util.*
import simphony.util.messages.*
import static java.lang.Math.*
import static repast.simphony.essentials.RepastEssentials.*

/**
 *
 * This is order agent.
 *
 */
public class Order  {

    /**
     *
     * The order owner, if not only one
     * @field owner
     *
     */
    @Parameter (displayName = "Owner", usageName = "owner")
    public ArrayList getOwner() {
        return owner
    }
    public void setOwner(ArrayList newValue) {
        owner = newValue
    }
    public ArrayList owner = new ArrayList()

    /**
     *
     * The order amount
     * @field amount
     *
     */
    @Parameter (displayName = "Amount", usageName = "amount")
    public int getAmount() {
        return amount
    }
    public void setAmount(int newValue) {
        amount = newValue
    }
    public int amount = 0

    /**
     *
     * Record the allocated service
     * @field allocatedService
     *
     */
    @Parameter (displayName = "Service", usageName = "allocatedService")
    public def getAllocatedService() {
        return allocatedService
    }
    public void setAllocatedService(def newValue) {
        allocatedService = newValue
    }
    public def allocatedService = null

    /**
     *
     * Record the candidates
     * @field candidates
     *
     */
    @Parameter (displayName = "Candidates", usageName = "candidates")
    public ArrayList getCandidates() {
        return candidates
    }
    public void setCandidates(ArrayList newValue) {
        candidates = newValue
    }
    public ArrayList candidates = new ArrayList()

    /**
     *
     * indicate if any of provider candidates
     * @field indicate
     *
     */
    @Parameter (displayName = "candidate indicate", usageName = "indicate")
    public boolean getIndicate() {
        return indicate
    }
    public void setIndicate(boolean newValue) {
        indicate = newValue
    }
    public boolean indicate = false

    /**
     *
     * This value is used to automatically generate agent identifiers.
     * @field serialVersionUID
     *
     */
    private static final long serialVersionUID = 1L

    /**
     *
     * This value is used to automatically generate agent identifiers.
     * @field agentIDCounter
     *
     */
    protected static long agentIDCounter = 1

    /**
     *
     * This value is the agent's identifier.
     * @field agentID
     *
     */
    protected String agentID = "Order " + (agentIDCounter++)

    /**
     *
     * Set the owner is add to the owner list
     * @method addOwner
     *
     */
    public void addOwner(String ownerID) {

        // Note the simulation time.
        def time = GetTickCountInTimeUnits()

        // add owner to the list
        this.owner.add(ownerID)
    }

    /**
     *
     * Chose the provider
     * @method Select
     *
     */
    @Watch(
        watcheeClassName = 'ecosystem.Order',
        watcheeFieldNames = 'indicate',
        triggerCondition = '$watcher.toString() == $watchee.toString() && $watchee.getIndicate()',
        whenToTrigger = WatcherTriggerSchedule.IMMEDIATE,
        scheduleTriggerDelta = 1d
    )
    public def Select(ecosystem.Order watchedAgent) {

        // This is a task.
        this.setAllocatedService(this.candidates.remove(0))
        this.allocatedService.setChose(true)
        this.getAllocatedService().setOrder(this)
        this.getAllocatedService().setRemain(this.getAmount())

        // This is a loop.
        for (Service s in this.candidates) {

            // This is a task.
            s.setCompete(false)

        }

        // This is a task.
        this.candidates.clear()
        this.setIndicate(false)
        this.allocatedService.setCompete(false)
        System.out.println("Chosed provider")
    }

    /**
     *
     * Add the competitor
     * @method AddCompetitor
     *
     */
    @Watch(
        watcheeClassName = 'ecosystem.Service',
        watcheeFieldNames = 'compete',
        triggerCondition = '$watchee.getCompete()',
        whenToTrigger = WatcherTriggerSchedule.IMMEDIATE,
        scheduleTriggerDelta = 1d
    )
    public def AddCompetitor(ecosystem.Service watchedAgent) {

        // Define the return value variable.
        def returnValue

        // Note the simulation time.
        def time = GetTickCountInTimeUnits()

        // Add to the temp candidates list
        this.candidates.add(watchedAgent)
        System.out.println("add competitor")

        // This is an agent decision.
        if (this.getIndicate()) {


        } else  {

            // Change the indicate
            this.setIndicate(true)

        }
        // Return the results.
        return returnValue

    }

    /**
     *
     * This method provides a human-readable name for the agent.
     * @method toString
     *
     */
    @ProbeID()
    public String toString() {

        // Define the return value variable.
        def returnValue

        // Note the simulation time.
        def time = GetTickCountInTimeUnits()

        // Set the default agent identifier.
        returnValue = this.agentID
        // Return the results.
        return returnValue

    }


}

